import {
  calculatePassengerChargeCents
} from "@/constants/pricing";
import {
  firestoreBaseUrl,
  firestoreCollectionUrl,
  firestoreDocumentUrl,
  runtimeConfig,
  withFirebaseApiKey,
} from "@/constants/runtime-config";
import { getAuth } from "firebase/auth";

// ─── Haversine ────────────────────────────────────────────────────────────────

function haversineKm(
  lat1: number,
  lon1: number,
  lat2: number,
  lon2: number,
): number {
  if ([lat1, lon1, lat2, lon2].some((v) => v == null || isNaN(v))) return 0;
  const R = 6371;
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLon = ((lon2 - lon1) * Math.PI) / 180;
  const a =
    Math.sin(dLat / 2) ** 2 +
    Math.cos((lat1 * Math.PI) / 180) *
      Math.cos((lat2 * Math.PI) / 180) *
      Math.sin(dLon / 2) ** 2;
  return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
}

// ─── Auth helpers ─────────────────────────────────────────────────────────────

async function getIdToken(): Promise<string> {
  const user = getAuth().currentUser;
  if (!user) throw new Error("Not authenticated");
  return user.getIdToken();
}

async function authHeaders(includeJson = false): Promise<Record<string, string>> {
  const token = await getIdToken();
  const headers: Record<string, string> = {
    Authorization: `Bearer ${token}`,
  };
  if (includeJson) headers["Content-Type"] = "application/json";
  return headers;
}

// ─── URL helpers ──────────────────────────────────────────────────────────────

const batchWriteUrl = (): string =>
  `${firestoreBaseUrl}:batchWrite`;

// ─── QR Token ─────────────────────────────────────────────────────────────────

/**
 * Generates a nonce, PATCHes the ride doc with qrToken/qrTokenExpiresAt,
 * and returns a Base64-encoded JSON payload.
 */
export async function generateQrToken(rideId: string): Promise<string> {
  const auth = getAuth();
  const user = auth.currentUser;
  if (!user) throw new Error("Not authenticated");

  const token = await user.getIdToken();
  const nonce = Math.random().toString(36).slice(2) + Math.random().toString(36).slice(2);
  const issuedAt = Date.now();
  const expiresAt = issuedAt + 10 * 60 * 1000; // 10 minutes

  // PATCH ride doc with qrToken and qrTokenExpiresAt
  const patchUrl = withFirebaseApiKey(
    `${firestoreDocumentUrl("rides", rideId)}?updateMask.fieldPaths=qrToken&updateMask.fieldPaths=qrTokenExpiresAt`,
  );

  const res = await fetch(patchUrl, {
    method: "PATCH",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
    },
    body: JSON.stringify({
      fields: {
        qrToken: { stringValue: nonce },
        qrTokenExpiresAt: { stringValue: new Date(expiresAt).toISOString() },
      },
    }),
  });

  if (!res.ok) {
    const errorText = await res.text().catch(() => "");
    throw new Error(`Failed to write QR token: ${errorText}`);
  }

  const payload = {
    rideId,
    driverUid: user.uid,
    issuedAt,
    expiresAt,
    nonce,
  };

  return btoa(JSON.stringify(payload));
}

// ─── Validate and Board Passenger ─────────────────────────────────────────────

/**
 * Decodes the Base64 QR payload, validates the nonce against Firestore,
 * checks the passenger is in passengers[] and NOT in boardedPassengers[],
 * then atomically appends to boardedPassengers.
 */
export async function validateAndBoardPassenger(
  qrPayload: string,
  passengerUid: string,
  expectedRideId?: string,
): Promise<void> {
  const token = await getIdToken();

  // Decode payload
  let parsed: {
    rideId: string;
    driverUid: string;
    issuedAt: number;
    expiresAt: number;
    nonce: string;
  };
  try {
    parsed = JSON.parse(atob(qrPayload));
  } catch {
    throw new Error("Invalid QR code format.");
  }

  const { rideId, driverUid, nonce, expiresAt } = parsed;

  // Verify this QR is for the expected ride
  if (expectedRideId && parsed.rideId !== expectedRideId) {
    throw new Error("This QR code is not for your ride.");
  }

  // Check expiry
  if (Date.now() > expiresAt) {
    throw new Error("QR code has expired. Ask your driver to regenerate it.");
  }

  // Fetch ride doc to validate nonce and passenger membership
  const rideUrl = withFirebaseApiKey(firestoreDocumentUrl("rides", rideId));
  const rideRes = await fetch(rideUrl, {
    headers: { Authorization: `Bearer ${token}` },
  });
  if (!rideRes.ok) throw new Error("Could not fetch ride data.");
  const rideData = await rideRes.json();

  const fields = rideData?.fields ?? {};

  // Verify QR was generated by the actual driver of this ride
  const actualDriverId: string = fields.driverId?.stringValue ?? "";
  if (driverUid !== actualDriverId) {
    throw new Error("This QR code was not generated by the driver of this ride.");
  }

  // Validate nonce
  const storedNonce: string = fields.qrToken?.stringValue ?? "";
  if (storedNonce !== nonce) {
    throw new Error("QR code is invalid or has been rotated.");
  }

  // Check passenger is in passengers[]
  const passengers: string[] =
    fields.passengers?.arrayValue?.values?.map((v: { stringValue: string }) => v.stringValue) ?? [];
  if (!passengers.includes(passengerUid)) {
    throw new Error("You are not a passenger on this ride.");
  }

  // Check not already boarded
  const boarded: string[] =
    fields.boardedPassengers?.arrayValue?.values?.map((v: { stringValue: string }) => v.stringValue) ?? [];
  if (boarded.includes(passengerUid)) {
    throw new Error("You have already boarded this ride.");
  }

  // Append passengerUid to boardedPassengers (read-merge-write)
  const updatedBoarded = [...boarded, passengerUid];
  const boardPatchUrl = withFirebaseApiKey(
    `${firestoreDocumentUrl("rides", rideId)}?updateMask.fieldPaths=boardedPassengers`,
  );
  const boardRes = await fetch(boardPatchUrl, {
    method: "PATCH",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
    },
    body: JSON.stringify({
      fields: {
        boardedPassengers: {
          arrayValue: {
            values: updatedBoarded.map((uid) => ({ stringValue: uid })),
          },
        },
      },
    }),
  });

  if (!boardRes.ok) {
    const errorText = await boardRes.text().catch(() => "");
    throw new Error(`Failed to board passenger: ${errorText}`);
  }
}

// ─── Process Ride Payments ────────────────────────────────────────────────────

/**
 * Full payment flow with idempotency guard.
 * 1. Fetch ride → guard if already processing/completed
 * 2. Set paymentStatus = "processing"
 * 3. Charge each boarded passenger
 * 4. Credit driver
 * 5. Set paymentStatus = "completed", distanceKm
 */
export async function processRidePayments(
  rideId: string,
  originCoords: { lat: number; lng: number },
  destCoords: { lat: number; lng: number },
): Promise<void> {
  const token = await getIdToken();

  // 1. Fetch ride doc
  const rideUrl = withFirebaseApiKey(firestoreDocumentUrl("rides", rideId));
  const rideRes = await fetch(rideUrl, {
    headers: { Authorization: `Bearer ${token}` },
  });
  if (!rideRes.ok) throw new Error("Failed to fetch ride for payment");
  const rideData = await rideRes.json();
  const fields = rideData?.fields ?? {};

  // 2. Idempotency guard
  const paymentStatus: string = fields.paymentStatus?.stringValue ?? "pending";
  if (paymentStatus === "completed" || paymentStatus === "processing") {
    return;
  }

  // 3. Optimistic lock — set to "processing"
  const lockUrl = withFirebaseApiKey(
    `${firestoreDocumentUrl("rides", rideId)}?updateMask.fieldPaths=paymentStatus`,
  );
  await fetch(lockUrl, {
    method: "PATCH",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
    },
    body: JSON.stringify({
      fields: { paymentStatus: { stringValue: "processing" } },
    }),
  });

  // 4. Calculate distance
  const distanceKm = haversineKm(
    originCoords.lat,
    originCoords.lng,
    destCoords.lat,
    destCoords.lng,
  );
  const chargePerPassenger = calculatePassengerChargeCents(distanceKm);

  const boardedPassengers: string[] =
    fields.boardedPassengers?.arrayValue?.values?.map(
      (v: { stringValue: string }) => v.stringValue,
    ) ?? [];

  const driverId: string = fields.driverId?.stringValue ?? "";

  const projectId = runtimeConfig.firebaseProjectId;
  const dbId = encodeURIComponent(runtimeConfig.firestoreDatabaseId);

  let totalEarnings = 0;

  // 5. Charge each passenger
  for (const uid of boardedPassengers) {
    try {
      // GET user wallet balance
      const userUrl = withFirebaseApiKey(firestoreDocumentUrl("users", uid));
      const userRes = await fetch(userUrl, {
        headers: { Authorization: `Bearer ${token}` },
      });
      if (!userRes.ok) continue;
      const userData = await userRes.json();
      const walletBalance: number = Number(
        userData?.fields?.walletBalance?.integerValue ?? 0,
      );

      if (walletBalance >= chargePerPassenger) {
        // Atomic decrement via batchWrite
        const passengerDocPath = `projects/${projectId}/databases/${dbId}/documents/users/${uid}`;
        const batchRes = await fetch(withFirebaseApiKey(batchWriteUrl()), {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${token}`,
          },
          body: JSON.stringify({
            writes: [
              {
                transform: {
                  document: passengerDocPath,
                  fieldTransforms: [
                    {
                      fieldPath: "walletBalance",
                      increment: { integerValue: String(-chargePerPassenger) },
                    },
                  ],
                },
              },
            ],
          }),
        });

        if (batchRes.ok) {
          totalEarnings += chargePerPassenger;
          await writeTransactionRecord(
            uid,
            {
              type: "ride_charge",
              amount: chargePerPassenger,
              status: "completed",
              description: `Ride charge for ride ${rideId}`,
              createdAt: new Date().toISOString(),
              rideId,
              distanceKm,
            },
            token,
          );
        }
      } else {
        // Insufficient balance — write failed transaction
        await writeTransactionRecord(
          uid,
          {
            type: "ride_charge",
            amount: chargePerPassenger,
            status: "failed",
            description: `Insufficient balance for ride ${rideId}`,
            createdAt: new Date().toISOString(),
            rideId,
            distanceKm,
          },
          token,
        );
      }
    } catch (e) {
      console.warn(`Payment failed for passenger ${uid}:`, e);
    }
  }

  // 6. Credit driver
  if (driverId && totalEarnings > 0) {
    try {
      const driverDocPath = `projects/${projectId}/databases/${dbId}/documents/users/${driverId}`;
      await fetch(withFirebaseApiKey(batchWriteUrl()), {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({
          writes: [
            {
              transform: {
                document: driverDocPath,
                fieldTransforms: [
                  {
                    fieldPath: "walletBalance",
                    increment: { integerValue: String(totalEarnings) },
                  },
                ],
              },
            },
          ],
        }),
      });

      await writeTransactionRecord(
        driverId,
        {
          type: "ride_earning",
          amount: totalEarnings,
          status: "completed",
          description: `Earnings for ride ${rideId} (${boardedPassengers.length} passenger(s))`,
          createdAt: new Date().toISOString(),
          rideId,
          distanceKm,
        },
        token,
      );
    } catch (e) {
      console.warn("Driver credit failed:", e);
    }
  }

  // 7. Finalize ride — set paymentStatus = "completed" and distanceKm
  const finalUrl = withFirebaseApiKey(
    `${firestoreDocumentUrl("rides", rideId)}?updateMask.fieldPaths=paymentStatus&updateMask.fieldPaths=distanceKm`,
  );
  await fetch(finalUrl, {
    method: "PATCH",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
    },
    body: JSON.stringify({
      fields: {
        paymentStatus: { stringValue: "completed" },
        distanceKm: { doubleValue: distanceKm },
      },
    }),
  });
}

// ─── Write Transaction Record ─────────────────────────────────────────────────

export async function writeTransactionRecord(
  uid: string,
  tx: object,
  token: string,
): Promise<void> {
  const url = withFirebaseApiKey(
    firestoreCollectionUrl(`users/${uid}/transactions`),
  );

  const txRecord = tx as Record<string, unknown>;

  const fields: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(txRecord)) {
    if (typeof value === "string") {
      fields[key] = { stringValue: value };
    } else if (typeof value === "number") {
      if (Number.isInteger(value)) {
        fields[key] = { integerValue: String(value) };
      } else {
        fields[key] = { doubleValue: value };
      }
    } else if (typeof value === "boolean") {
      fields[key] = { booleanValue: value };
    }
  }

  await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
    },
    body: JSON.stringify({ fields }),
  });
}

// ─── Get Ride Payment Data ────────────────────────────────────────────────────

export async function getRidePaymentData(
  rideId: string,
  token: string,
): Promise<{ boardedPassengers: string[]; paymentStatus: string; driverId: string }> {
  const rideUrl = withFirebaseApiKey(firestoreDocumentUrl("rides", rideId));
  const res = await fetch(rideUrl, {
    headers: { Authorization: `Bearer ${token}` },
  });
  if (!res.ok) throw new Error("Failed to fetch ride payment data");
  const data = await res.json();
  const fields = data?.fields ?? {};

  const boardedPassengers: string[] =
    fields.boardedPassengers?.arrayValue?.values?.map(
      (v: { stringValue: string }) => v.stringValue,
    ) ?? [];
  const paymentStatus: string = fields.paymentStatus?.stringValue ?? "pending";
  const driverId: string = fields.driverId?.stringValue ?? "";

  return { boardedPassengers, paymentStatus, driverId };
}
