import {
  apiFetch,
  apiBaseUrl,
  firestoreDocumentUrl,
  withFirebaseApiKey,
} from "@/constants/runtime-config";
import { getAuth } from "firebase/auth";

// ─── Auth helpers ─────────────────────────────────────────────────────────────

async function getIdToken(): Promise<string> {
  const user = getAuth().currentUser;
  if (!user) throw new Error("Not authenticated");
  return user.getIdToken();
}

// ─── QR Token ─────────────────────────────────────────────────────────────────

/**
 * Generates a nonce, PATCHes the ride doc with qrToken/qrTokenExpiresAt,
 * and returns a Base64-encoded JSON payload.
 */
export async function generateQrToken(rideId: string): Promise<string> {
  const auth = getAuth();
  const user = auth.currentUser;
  if (!user) throw new Error("Not authenticated");

  const token = await user.getIdToken();
  const nonce = Math.random().toString(36).slice(2) + Math.random().toString(36).slice(2);
  const issuedAt = Date.now();
  const expiresAt = issuedAt + 10 * 60 * 1000; // 10 minutes

  const patchUrl = withFirebaseApiKey(
    `${firestoreDocumentUrl("rides", rideId)}?updateMask.fieldPaths=qrToken&updateMask.fieldPaths=qrTokenExpiresAt`,
  );

  const res = await fetch(patchUrl, {
    method: "PATCH",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
    },
    body: JSON.stringify({
      fields: {
        qrToken: { stringValue: nonce },
        qrTokenExpiresAt: { stringValue: new Date(expiresAt).toISOString() },
      },
    }),
  });

  if (!res.ok) {
    const errorText = await res.text().catch(() => "");
    throw new Error(`Failed to write QR token: ${errorText}`);
  }

  return btoa(JSON.stringify({ rideId, driverUid: user.uid, issuedAt, expiresAt, nonce }));
}

// ─── Validate and Board Passenger ─────────────────────────────────────────────

/**
 * Decodes the Base64 QR payload, validates the nonce against Firestore,
 * checks the passenger is in passengers[] and NOT in boardedPassengers[],
 * then atomically appends to boardedPassengers.
 */
export async function validateAndBoardPassenger(
  qrPayload: string,
  passengerUid: string,
  expectedRideId?: string,
): Promise<void> {
  const token = await getIdToken();

  let parsed: {
    rideId: string;
    driverUid: string;
    issuedAt: number;
    expiresAt: number;
    nonce: string;
  };
  try {
    parsed = JSON.parse(atob(qrPayload));
  } catch {
    throw new Error("Invalid QR code format.");
  }

  const { rideId, driverUid, nonce, expiresAt } = parsed;

  if (expectedRideId && parsed.rideId !== expectedRideId) {
    throw new Error("This QR code is not for your ride.");
  }

  if (Date.now() > expiresAt) {
    throw new Error("QR code has expired. Ask your driver to regenerate it.");
  }

  const rideUrl = withFirebaseApiKey(firestoreDocumentUrl("rides", rideId));
  const rideRes = await fetch(rideUrl, {
    headers: { Authorization: `Bearer ${token}` },
  });
  if (!rideRes.ok) throw new Error("Could not fetch ride data.");
  const rideData = await rideRes.json();

  const fields = rideData?.fields ?? {};

  const actualDriverId: string = fields.driverId?.stringValue ?? "";
  if (driverUid !== actualDriverId) {
    throw new Error("This QR code was not generated by the driver of this ride.");
  }

  const storedNonce: string = fields.qrToken?.stringValue ?? "";
  if (storedNonce !== nonce) {
    throw new Error("QR code is invalid or has been rotated.");
  }

  const passengers: string[] =
    fields.passengers?.arrayValue?.values?.map((v: { stringValue: string }) => v.stringValue) ?? [];
  if (!passengers.includes(passengerUid)) {
    throw new Error("You are not a passenger on this ride.");
  }

  const boarded: string[] =
    fields.boardedPassengers?.arrayValue?.values?.map((v: { stringValue: string }) => v.stringValue) ?? [];
  if (boarded.includes(passengerUid)) {
    throw new Error("You have already boarded this ride.");
  }

  const updatedBoarded = [...boarded, passengerUid];
  const boardPatchUrl = withFirebaseApiKey(
    `${firestoreDocumentUrl("rides", rideId)}?updateMask.fieldPaths=boardedPassengers`,
  );
  const boardRes = await fetch(boardPatchUrl, {
    method: "PATCH",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
    },
    body: JSON.stringify({
      fields: {
        boardedPassengers: {
          arrayValue: {
            values: updatedBoarded.map((uid) => ({ stringValue: uid })),
          },
        },
      },
    }),
  });

  if (!boardRes.ok) {
    const errorText = await boardRes.text().catch(() => "");
    throw new Error(`Failed to board passenger: ${errorText}`);
  }
}

// ─── Process Ride Payments ────────────────────────────────────────────────────

/**
 * Delegates all payment logic to the server-side /rides/complete endpoint.
 * Only confirmed drop-off passengers (overridePassengers) are charged.
 */
export async function processRidePayments(
  rideId: string,
  _originCoords: { lat: number; lng: number },
  _destCoords: { lat: number; lng: number },
  _passengerPickups?: Record<string, { lat: number; lng: number }>,
  overridePassengers?: string[],
): Promise<void> {
  const token = await getIdToken();

  const res = await apiFetch(`${apiBaseUrl}/rides/complete`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
    },
    body: JSON.stringify({
      rideId,
      confirmedPassengerIds: overridePassengers ?? [],
    }),
  });

  if (!res.ok) {
    const text = await res.text().catch(() => "");
    throw new Error(`Ride completion failed: ${text}`);
  }
}
